config/routes.rb
Rails.application.routes.draw do

  resources :databases do
    resources :tables do
      resources :columns
    end
  end
  root 'databases#index'
  get 'tables/superlist' => 'tables#superlist'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :table
end

app/models/database.rb
class Database < ApplicationRecord
  has_many :tables
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :database
  has_many :columns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @database = Database.find(params[:database_id])
    @table = @database.tables.find(params[:table_id])
    @column = @table.columns.build
  end

  def create
    @table = Table.find(params[:table_id])
    @column = @table.columns.new(column_params)

    if @column.save
      @database = @table.database
      redirect_to database_table_path(@database.id, @table.id)
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  private

    def column_params
      params.require(:column).permit(:name, :datatype)
    end
end

app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
  def index
    @databases = Database.all
  end

  def new
    @database = Database.new
  end

  def show
    @database = Database.find(params[:id])
  end

  def create
    @database = Database.new(database_params)

    if @database.save
      flash[:notice] = "New database saved to list"
      redirect_to databases_path
    else
      flash[:error] = "Something went wrong, check logs"
      redirect_to databases_path
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  private

    def database_params
      params.require(:database).permit(:name, :description)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @database = Database.find(params[:database_id])
    @tables = @database.tables
  end

  def show
    @table = Table.find(params[:id])
    @database = @table.database
    @columns = @table.columns.order('name ASC')
  end

  def new
    @database = Database.find(params[:database_id])
    @table = @database.tables.build
  end

  def create
    @database = Database.find(params[:database_id])
    @table = @database.tables.new(table_params)
    if @table.save
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  def superlist
    @tables = Table.all
  end

  private

    def table_params
      params.require(:table).permit(:name, :tabletype, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/databases_helper.rb
module DatabasesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/columns/create.html.erb
<h1>Columns#create</h1>
<p>Find me in app/views/columns/create.html.erb</p>

app/views/columns/delete.html.erb
<h1>Columns#delete</h1>
<p>Find me in app/views/columns/delete.html.erb</p>

app/views/columns/edit.html.erb
<h1>Columns#edit</h1>
<p>Find me in app/views/columns/edit.html.erb</p>

app/views/columns/index.html.erb
<h1>Columns#index</h1>
<p>Find me in app/views/columns/index.html.erb</p>

app/views/columns/new.html.erb
<div class="container">
  <div class="row">
    <h4 class="text-center">New column for <%= @database.name %>.<%= @table.name %></h4>
  </div>
  <br>
  <%= form_for([@database, @table, @column]) do |f| %>
    <div class="row">
      <%= f.label :name, :class => "col-sm-1 col-sm-offset-2"  %>
      <%= f.text_field :name, :class => "col-sm-6" %>
    </div>
    <br>
    <div class="row">
      <%= f.label :datatype, :class => "col-sm-1 col-sm-offset-2"  %>
      <%= f.text_field :datatype, :class => "col-sm-6" %>
    </div>
    <br>
    <div class="row">
      <%= f.submit "Add Column", :class => "col-sm-2 col-sm-offset-5 btn btn-primary btn-sm" %>
    </div>
  <% end %>
</div>

app/views/columns/show.html.erb
<h1>Columns#show</h1>
<p>Find me in app/views/columns/show.html.erb</p>

app/views/columns/update.html.erb
<h1>Columns#update</h1>
<p>Find me in app/views/columns/update.html.erb</p>

app/views/databases/_new_db_form.html.erb
<%= form_for(@database) do |f| %>
<div class="row">
  <%= f.label :name, :class => "col-sm-1 col-sm-offset-2" %>
  <%= f.text_field :name, :class => "col-sm-6" %>
</div>
<br>
<div class="row">
  <%= f.label :description, :class => "col-sm-1 col-sm-offset-2" %>
  <%= f.text_field :description, :size => 80, :class => "col-sm-6" %>
</div>
<br>
<div class="row">
  <%= f.submit "Add Database", :class => "col-sm-2 col-sm-offset-5 btn btn-primary btn-sm" %>
</div>
<% end %>

app/views/databases/create.html.erb
<h1>Databases#create</h1>
<p>Find me in app/views/databases/create.html.erb</p>

app/views/databases/delete.html.erb
<h1>Databases#delete</h1>
<p>Find me in app/views/databases/delete.html.erb</p>

app/views/databases/edit.html.erb
<h1>Databases#edit</h1>
<p>Find me in app/views/databases/edit.html.erb</p>

app/views/databases/index.html.erb
<div class="container">
  <div class="row">
  <h3 class="text-center">Databases</h3>
  </div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <table class="table">
        <thead>
          <th>Database</th>
          <th>Description</th>
          <th>Link to Tables</th>
        </thead>
        <tbody>
          <% @databases.each do |db| %>
            <tr>
              <td><%= db.name %></td>
              <td><%= db.description %></td>
              <td><%= link_to db.name, database_tables_path(db.id), :'data-toggle' => "tooltip", :'data-placement' => 'top', :'title' => "Click to see #{db.name} tables"  %></td>
            </tr>
          <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <h5 class="text-center"><%= link_to "Add A Database", new_database_path, :class => "btn btn-primary btn-sm" %></h5>
  </div>
</div>

app/views/databases/new.html.erb
<div class="container">
  <div class= "row">
    <h3 class="text-center">Add a database to the list</h3>
  </div>
    <%= render 'databases/new_db_form' %>
</div>

app/views/databases/show.html.erb
<h1>Databases#show</h1>
<p>Find me in app/views/databases/show.html.erb</p>

app/views/databases/update.html.erb
<h1>Databases#update</h1>
<p>Find me in app/views/databases/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SqlBuilder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h6 class="text-center"><%= link_to "Home", root_path %> | <%= link_to "Databases", databases_path %> | <%= link_to "Tables", tables_superlist_path %></h6>
    <%= yield %>
    <div style="position:fixed; bottom:0px;">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/tables/create.html.erb
<h1>Tables#create</h1>
<p>Find me in app/views/tables/create.html.erb</p>

app/views/tables/delete.html.erb
<h1>Tables#delete</h1>
<p>Find me in app/views/tables/delete.html.erb</p>

app/views/tables/edit.html.erb
<h1>Tables#edit</h1>
<p>Find me in app/views/tables/edit.html.erb</p>

app/views/tables/index.html.erb
<div class="container">
  <div class="row">
  <h3 class="text-center"><%= @database.name %> Tables</h3>
  </div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <table class="table">
        <thead>
          <th>Table</th>
          <th>Type</th>
          <th>Description</th>
        </thead>
        <tbody>
          <% @tables.each do |t| %>
            <tr>
              <td><%= link_to t.name, database_table_path(@database.id, t.id), :'data-toggle' => "tooltip", :'data-placement' => 'top', :'title' => "Click to see #{t.name} columns" %></td>
              <td><%= t.tabletype %></td>
              <td><%= t.description %></td>
            </tr>
          <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <h5 class="text-center"><%= link_to "Add A Table", new_database_table_path(@database.id) %></h5>
  </div>
</div>

app/views/tables/new.html.erb
<div class="container">
  <%= form_for([@database, @table]) do |f| %>
    <div class="row">
      <%= f.label :name, :class => "col-sm-1 col-sm-offset-2" %>
      <%= f.text_field :name, :class => "col-sm-3" %>
      <%= f.label :tabletype, :class => "col-sm-1" %>
      <%= f.text_field :tabletype, :class => "col-sm-2" %>
    </div>
    <div class="row">
      <%= f.label :description, :class => "col-sm-1 col-sm-offset-2" %>
      <%= f.text_field :description, :class => "col-sm-6" %>
    </div>
    <div class="row">
    </div>
    <div class="row">
      <%= f.submit "Add Table", :class => "col-sm-2 col-sm-offset-5" %>
    </div>
  <% end %>
</div>

app/views/tables/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center"><%= link_to @table.database.name, database_path(@table.database.id) %>.<%= link_to @table.name, database_table_path(@table.database.id, @table.id) %></h3>
  </div>
  <br>
  <div class="row">
    <h5 class="text-center"><%= link_to "Add a column", new_database_table_column_path(@database.id, @table.id), :class => "btn btn-danger btn-sm" %></h5>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <table class="table">
        <thead>
          <th>Column</th>
          <th>datatype</th>
        </thead>
        <tbody>
          <% @columns.each do |c|  %>
            <tr>
              <td><%= c.name %></td>
              <td><%= c.datatype %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
  </div>

</div>

app/views/tables/superlist.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Tables</h3>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <table class="table table-hover table-sm">
        <thead class="thead-inverse">
          <th>Table name</th>
          <th>Database</th>
        </thead>
        <tbody>
          <% @tables.each do |t| %>
            <tr>
              <td><%= t.name %></td>
              <td><%= link_to t.database.name, database_path(t.database.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tables/update.html.erb
<h1>Tables#update</h1>
<p>Find me in app/views/tables/update.html.erb</p>